### ISSUE TITLE
Parameterize workflow and set values in deploy action

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/clinvar-ingest#77]

**Comment by theferrit32** [comment]
Don't really want to pull in a fancy templating library for this. Just going to use python formatting to format the file as a string

e.g.
```bash
$ cat test.yaml
step:
  name: {step_name}
$ step_name="Kyle's step" python -c "import os; print(open('test.yaml').read().format(**os.environ))"
step:
  name: Kyle's step

```

**Comment by theferrit32** [comment]
This idea may be problematic because the workflow itself has things that look like python `str.format` templates.
```yaml
main:
    params: [args]
    steps:
        - copy:
            call: http.post
            args:
                url: ...
                body: '${args}'
                auth:
                    type: OIDC
            result: copy_result
        - parse:
            call: http.post
            args:
                url: ...
                body: '${copy_result.body}'
                auth:
                    type: OIDC
            result: parse_result
        - result:
            return: ${parse_result}
```
